---
kind: pipeline
type: docker
name: lab3

steps:
  - name: cowsay_greetings
    image: alpine
    commands:
      - apk update
      - apk add --no-cache git perl
      - cd /tmp 
      - git clone https://github.com/jasonm23/cowsay.git 
      - cd cowsay ; ./install.sh /usr/local
      - /usr/local/bin/cowsay "Lab 3 Antsybor"


  - name: build_app 
    image: gcc:latest 
    commands:
      - g++ -o program program.cpp

  - name: app_test
    image: python:3.10
    commands:
      - python test.py

  - name: cleanup
    image: alpine
    commands:
      - rm -rf /var/cache/apk/* /var/tmp/* /tmp/* 
      - rm -rf cowsay_greetings/
      - echo "Cleanup completed"
      - rm -rf build_app/
#
# - name: build
#   image: gcc:latest
#   commands:
#     - g++ -o hello_cpp hello.cpp
#     - ./hello_cpp

# - name: test-python
#   image: python:3.10
#   commands:
#     - python test.py


  
trigger:
  branch:
  - main
