---
kind: pipeline
type: docker
name: lab3

steps:
  - name: cowsay_install
    image: alpine
    commands:
      - apk update
      - apk add --no-cache git perl
      - cd /tmp 
      - git clone https://github.com/jasonm23/cowsay.git 
      - cd cowsay ; ./install.sh /usr/local
      - rm -rf /var/cache/apk/* /var/tmp/* /tmp/* 
      - apk del git

  - name: cowsay_greetings
    image: alpine
    pull: never
    commands:
      - apk add -U --no-cache perl
      - COPY --from=build /usr/local/bin/cowsay /usr/local/bin/
      - /usr/local/bin/cowsay "Lab 3 Antsybor"
    depends_on:
      - cowsay_install
#     


# - name: build
#   image: gcc:latest
#   commands:
#     - g++ -o hello_cpp hello.cpp
#     - ./hello_cpp

# - name: test-python
#   image: python:3.10
#   commands:
#     - python test.py

# - name: lint-python
#   image: python:3.10
#   commands:
#     - pip install pylint
#     - pylint script.py

# - name: cleanup
#   image: alpine
#   commands:
#     - rm -rf build/
#     - echo "Cleanup completed"
 
trigger:
  branch:
  - main
